### ISSUE TITLE
Last session says Running even though i was Walking

### ISSUE THREAD

**Issue by protorion** [tderflinger/MMM-GConnect#1]
Hi, Not sure if this is an issue or simply the way it is but I did my first test just now and even though Garmin Connect says Walking, MMM-GConnect says Running.

Thanks for a great module.

BR Henrik

**Comment by tderflinger** [comment]
Hi Henrik,

thanks for using MMM-GConnect, glad you like it. "Running" is a static text since I use it only for running. I will look into this, if there is a way in the API to find out the sports mode. Once I fix that I will let you know.

Kind regards,
-Thomas

**Comment by tderflinger** [comment]
Hi Henrik,

I now fixed the issue. The sports mode is read from the API and displayed. Please let me know if that works for you.

Best,
-Thomas

**Comment by protorion** [comment]
I saw the update-notification on my mirror when I woke up today. Awesome! Thanks! :)
