### ISSUE TITLE
Unable to use this widget

### ISSUE THREAD

**Issue by ashvinpanicker** [tderflinger/MMM-GConnect#3]
When I enable this module in my config, None of the basic magic mirror modules are rendered on screen, including the clock, calendar, news, etc.

In the logs I'm getting this error:

`Cannot read properties of undefined (reading 'startTimeLocal') at getLastActivityDate` from **nodeHelper.js:28**

**Comment by crisvdn** [comment]
I'm running version v2.25.0 of MagicMirror and this module works. Check your version and maybe post your config?

**Comment by tderflinger** [comment]
@ashvinpanicker, do you already have logged any activity in your Garmin account? Please also check that the login data (loginName and password) is correct. Else, please try it again with the latest version of Magic Mirror and MMM-Garmin. If it still does not work, please let me know.

**Comment by ashvinpanicker** [comment]
Thank you for your response! Since I've changed my smartwatch from Garmin, I've decided I do not need to use the module anymore, so I'll go ahead and close this issue. Appreciate your help, and best of luck with the project!
